const express = require("express")
const mongoose = require("mongoose")
const helmet = require("helmet")
const rateLimit = require("express-rate-limit")
const cors = require("cors")
const dotenv = require("dotenv")
dotenv.config()
const app = express()
app.use(helmet())
app.use(cors())
app.use(express.json())
const limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 })
app.use(limiter)
mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log("MongoDB connected"))
  .catch(err => console.error("MongoDB error:", err))
app.use("/api/auth", require("./routes/auth"))
app.use("/api/posts", require("./routes/posts"))
app.use("/api/comments", require("./routes/comments"))
app.use("/api/users", require("./routes/users"))
app.use("/api/favorites", require("./routes/favorites"))
app.use("/api/admin", require("./routes/admin"))
app.use("/api/search", require("./routes/search"))
module.exports = app
