const express = require("express")
const router = express.Router()
const authMiddleware = require("../middleware/authMiddleware")
const { createPost, getPosts, getPostById, likePost, getPopularPosts, deletePost } = require("../controllers/postController")
router.get("/popular", getPopularPosts)
router.get("/", getPosts)
router.get("/:id", getPostById)
router.post("/", authMiddleware, createPost)
router.post("/:id/like", authMiddleware, likePost)
router.delete("/:id", authMiddleware, deletePost)
module.exports = router
